from models import Profile


profiles = [
    {'name': 'Enol-Fernandez-delCastillo',
     'email': 'enolfc@ifca.unican.es',
     'country': 'ES',
     'institution': 'IFCA',
     'phone': '+34942202084',
     'user_dn': '/DC=es/DC=irisgrid/O=ifca/CN=Enol-Fernandez-delCastillo'
     },
    {'name': 'Isabel-Campos-Plasencia',
     'email': 'isabel@campos-it.es',
     'country': 'ES',
     'institution': 'CSIC',
     'phone': '942201343',
     'user_dn': '/DC=es/DC=irisgrid/O=ifca/CN=Isabel-Campos-Plasencia',
     },
    {'name': 'alvarosimon',
     'email': 'asimon@cesga.es',
     'country': 'ES',
     'institution': 'CESGA',
     'phone': '+34981569810',
     'user_dn': '/DC=es/DC=irisgrid/O=cesga/CN=alvarosimon',
     },
    {'name': 'Joao Antonio Tomasio Pina',
     'email': 'jpina@lip.pt',
     'country': 'PT',
     'institution': 'LIP LISBOA',
     'phone': '(+351) 21 797 38 80',
     'user_dn': '/C=PT/O=LIPCA/O=LIP/OU=Lisboa/CN=Joao Antonio Tomasio Pina',
     },
    {'name': 'Mario David',
     'email': 'david@lip.pt',
     'country': 'PT',
     'institution': 'LIP LISBOA',
     'phone': '+351 217973880',
     'user_dn': '/C=PT/O=LIPCA/O=LIP/OU=Lisboa/CN=Mario David',
     },
    {'name': 'Marcus Hardt',
     'email': 'hardt@kit.edu',
     'country': 'DE',
     'institution': 'KIT',
     'phone': '+4972124659',
     'user_dn': '/C=DE/O=GermanGrid/OU=KIT/CN=Marcus Hardt',
     },
    {'name': 'miguel-caballer',
     'email': 'micafer1@upv.es',
     'country': 'ES',
     'institution': 'UPV',
     'phone': '963877007 ext. 88254',
     'user_dn': '/DC=es/DC=irisgrid/O=upv/CN=miguel-caballer',
     },
    {'name': 'Miguel-Angel-Nunez-Vega',
     'email': 'manunez@ifca.unican.es',
     'country': 'ES',
     'institution': 'IFCA',
     'phone': '+34668886621',
     'user_dn': '/DC=es/DC=irisgrid/O=ifca/CN=Miguel-Angel-Nunez-Vega',
     },
    {'name': 'german.molto',
     'email': 'gmolto@dsic.upv.es',
     'country': 'ES',
     'institution': 'I3M-UPV',
     'phone': '+34963877007 Ext. 88254',
     'user_dn': '/DC=es/DC=irisgrid/O=upv/CN=german.molto',
     },
    {'name': 'Miguel Angel',
     'email': 'manvac@gmail.com',
     'country': 'ES',
     'institution': 'IFCA',
     'phone': '668886621',
     },
    {'name': 'luis-cabellos',
     'email': 'cabellos@ifca.unican.es',
     'country': 'ES',
     'institution': 'IFCA',
     'phone': '942201404',
     'user_dn': '/DC=es/DC=irisgrid/O=ifca/CN=luis-cabellos',
     },
    {'name': 'alvaro-lopez',
     'email': 'aloga@ifca.unican.es',
     'country': 'ES',
     'institution': 'IFCA',
     'phone': '+34942200969',
     'user_dn': '/DC=es/DC=irisgrid/O=ifca/CN=alvaro-lopez',
     },
    {'name': 'Enol',
     'email': 'enolfc@gmail.com',
     'country': 'ES',
     'institution': 'IFCA',
     'phone': '+34942202094',
     },
    {'name': 'Jesus.Marco.deLucas',
     'email': 'marco@ifca.unican.es',
     'country': 'ES',
     'institution': 'CSIC',
     'phone': '942201458',
     'user_dn': '/DC=es/DC=irisgrid/O=ifca/CN=Jesus.Marco.deLucas',
     },
    {'name': 'Andres Gomez',
     'email': 'agomez@cesga.es',
     'country': 'ES',
     'institution': 'CESGA',
     'phone': '34 981569810',
     },
    {'name': 'mdserrano',
     'email': 'mdserrano@ugr.es',
     'country': 'ES',
     'institution': 'University of Granada',
     'phone': '+34958242759',
     'user_dn': '/DC=es/DC=irisgrid/O=ugr/CN=mdserrano',
     },
    {'name': 'miguel-diaz',
     'email': 'miguelangel.diaz@ciemat.es',
     'country': 'ES',
     'institution': 'CETA-CIEMAT',
     'phone': '0034 927 65 93 17',
     'user_dn': '/DC=es/DC=irisgrid/O=ceta-ciemat/CN=miguel-diaz',
     },
    {'name': 'gines.rubio',
     'email': 'grubio@ugr.es',
     'country': 'ES',
     'institution': 'University of Granada',
     'phone': '034958241725',
     'user_dn': '/DC=es/DC=irisgrid/O=ugr/CN=gines.rubio',
     },
]

for p in profiles:
    p['status'] = Profile.CONFIRMED
    Profile.objects.new_profile(**p)
